name: Upload To Azure WEB Static
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: feeloor/azure-static-website-deploy@master
        env:
          SOURCE_DIR: "./delta-budget-tracker"
          AZURE_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
          AZURE_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_STORAGE_ACCOUNT_NAME: "budgetrackerfront"
          AZURE_INDEX_DOCUMENT_NAME: "index.html"
          FORCE_OVERWRITE: "true"
